-- phân trang: 
SELECT P.ID, P.SKU, P.TITLE, P.PRICE, P.SALEPRICE, P.FEATUREDIMAGE, 
	GROUP_CONCAT(DISTINCT G.GALLAREY SEPARATOR ', ') AS GALLAREYS,
	P.DESCRIPT, P.CREADTEDDATE, P.MODIFIEDDATE,
        GROUP_CONCAT(DISTINCT C.CATEGORY SEPARATOR ', ') AS CATEGORIES,
        GROUP_CONCAT(DISTINCT T.TAG SEPARATOR ', ') AS TAGS
FROM PRODUCTS 		AS P
INNER JOIN CATEGORYS 	AS C
INNER JOIN TAGS		AS T
INNER JOIN GALLAREYS	AS G
ON 
	P.ID = C.ID 
	AND P.ID = T.ID 
    	AND P.ID = G.ID
GROUP BY P.ID
LIMIT 2 OFFSET 0;

SELECT P.ID, P.SKU, P.TITLE, P.PRICE, P.SALEPRICE, P.FEATUREDIMAGE, 
	GROUP_CONCAT(DISTINCT G.GALLAREY SEPARATOR ', ') AS GALLAREYS,
	P.DESCRIPT, P.CREADTEDDATE, P.MODIFIEDDATE,
        GROUP_CONCAT(DISTINCT C.CATEGORY SEPARATOR ', ') AS CATEGORIES,
        GROUP_CONCAT(DISTINCT T.TAG SEPARATOR ', ') AS TAGS
FROM PRODUCTS 		AS P
INNER JOIN CATEGORYS 	AS C
INNER JOIN TAGS		AS T
INNER JOIN GALLAREYS	AS G
ON 
	P.ID = C.ID 
	AND P.ID = T.ID 
    	AND P.ID = G.ID
GROUP BY P.ID
LIMIT 2 OFFSET 2;

SELECT P.ID, P.SKU, P.TITLE, P.PRICE, P.SALEPRICE, P.FEATUREDIMAGE, 
	GROUP_CONCAT(DISTINCT G.GALLAREY SEPARATOR ', ') AS GALLAREYS,
	P.DESCRIPT, P.CREADTEDDATE, P.MODIFIEDDATE,
        GROUP_CONCAT(DISTINCT C.CATEGORY SEPARATOR ', ') AS CATEGORIES,
        GROUP_CONCAT(DISTINCT T.TAG SEPARATOR ', ') AS TAGS
FROM PRODUCTS 		AS P
INNER JOIN CATEGORYS 	AS C
INNER JOIN TAGS		AS T
INNER JOIN GALLAREYS	AS G
ON 
	P.ID = C.ID 
	AND P.ID = T.ID 
    	AND P.ID = G.ID
GROUP BY P.ID
LIMIT 2 OFFSET 4;


-- hiển thị ds theo tag
SELECT P.ID, P.SKU, P.TITLE, P.PRICE, P.SALEPRICE, P.FEATUREDIMAGE, 
	GROUP_CONCAT(DISTINCT G.GALLAREY SEPARATOR ', ') AS GALLAREYS,
	P.DESCRIPT, P.CREADTEDDATE, P.MODIFIEDDATE,
        GROUP_CONCAT(DISTINCT C.CATEGORY SEPARATOR ', ') AS CATEGORIES,
        GROUP_CONCAT(DISTINCT T.TAG SEPARATOR ', ') AS TAGS
FROM PRODUCTS 		AS P
INNER JOIN CATEGORYS 	AS C
INNER JOIN TAGS		AS T
INNER JOIN GALLAREYS	AS G
ON 
	P.ID = C.ID 
	AND P.ID = T.ID 
    	AND P.ID = G.ID
GROUP BY P.ID
HAVING FIND_IN_SET('sale', GROUP_CONCAT(DISTINCT T.TAG));


SELECT P.ID, P.SKU, P.TITLE, P.PRICE, P.SALEPRICE, P.FEATUREDIMAGE, 
		GROUP_CONCAT(DISTINCT G.GALLAREY SEPARATOR ', ') AS GALLAREYS,
		P.DESCRIPT, P.CREADTEDDATE, P.MODIFIEDDATE,
        GROUP_CONCAT(DISTINCT C.CATEGORY SEPARATOR ', ') AS CATEGORIES,
		GROUP_CONCAT(DISTINCT T.TAG SEPARATOR ', ') AS TAGS
FROM PRODUCTS 		AS P
INNER JOIN CATEGORYS 	AS C
INNER JOIN TAGS		AS T
INNER JOIN GALLAREYS	AS G
ON 
	P.ID = C.ID 
	AND P.ID = T.ID 
    	AND P.ID = G.ID
GROUP BY P.ID
HAVING FIND_IN_SET('Beauty', GROUP_CONCAT(DISTINCT C.CATEGORY));